# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-django-111
    - python: 3.4
      env: TOX_ENV=py34-django-111
    - python: 3.4
      env: TOX_ENV=py34-django-20
    - python: 3.5
      env: TOX_ENV=py35-django-111
    - python: 3.5
      env: TOX_ENV=py35-django-20
    - python: 3.6
      env: TOX_ENV=py36-django-111
    - python: 3.6
      env: TOX_ENV=py36-django-20
    - python: 3.6
      env: TOX_ENV=py36-django-22
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
