name: Django GetPaid CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: tests.settings
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.10'
            tox-env: py310-django52
          - python-version: '3.11'
            tox-env: py311-django52
          - python-version: '3.12'
            tox-env: py312-django52
          - python-version: '3.13'
            tox-env: py313-django52
          - python-version: '3.13'
            tox-env: py313-django60
          - python-version: '3.14'
            tox-env: py314-django52
          - python-version: '3.14'
            tox-env: py314-django60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tests via tox
        run: tox -e ${{ matrix.tox-env }}
